require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TagsController do
  def mock_tag
    @models ||= ['tag1','tag2']
  end

  describe "GET programs" do
    it "assigns the requested tag as @tag" do
      Video.stub(:containing_tag).with("coffee") { mock_tag }
      get :search, :term => "coffee"
      assigns(:tags).should == mock_tag
    end
  end
end
